---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/19 17:49
---

require("function")
Object = {}
Object.name = "one obj:"
function Object:new()
    local obj = {}
    self.__index = self
    setmetatable(obj,self)
    return obj
end
deLog("继承")
-- 在该脚本中创建一个全局变量的表,这个表也有new功能
function Object:subClass(className)
    _G[className] = {}
    self.__index = self   --设置index为self
    setmetatable(_G[className],self)
end

Object:subClass("Person")   --创建一个继承于object的person类
Person.name = Person.name.."person"
Object:subClass("Monster")  --创建一个继承于object的monster类
Monster.name = Monster.name.."monster"

local p = Person:new()
p.name = "info:"..p.name
local m = Monster:new()
m.name = "info:"..m.name
print(p.name)
print(m.name)

-- P相当于把Object的子表Person作为元表，当P找不到name时，会寻找Person有没有name
-- Person也没有name时，寻找Object是否有name，再没有时，返回nil


