---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/15 17:16
---

require("function")

deLog("特殊用法")
deLog("多变量赋予")
a,b,c = 1,2,3,4,5         --多变量赋予时，如果前面的值不够，会把多余的未赋予的值省略
print(a)print(b)print(c)  --如果需要未赋予的值不够时，给需要赋予的值补空

deLog("and or")
--  逻辑与 逻辑或
--  and or 他们不仅可以连接 boolean 任何东西都可以用来连接
--  在lua中 只有 nil 和 false 才认为是假
--  and相当于短路，当前面为真的时候就直接返回，不判断后面的逻辑
print(1 and 2)
print(nil and  1)
print(false and 2 )
print(1 and false)

print(nil or  1)
print(false or true )
print(1 or false)

deLog("三目运算符")
-- 三目运算符在C#中是: ? :
x = 1
y = 2
local res = (x>y) and x or y --三目运算符，其实就相当于先判断前面的and，在把and的结果和后面判断

print(res)


