---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/11 22:40
---
---迭代器

--ipairs不能找到0和0以下的自定义索引；从1开始索引，如果后面有索引短了，那么剩下的值也找不到
print("**********ipairs迭代器*************")
aa = {[0]=1,2,3,[3]=4,5,[9]=6}
for k,v in ipairs(aa) do
    print("ipairs迭代器遍历："..k.."_"..v)
end

--pairs可以找到表中的全部索引。无法覆盖lua自定义的索引
print("**********pairs迭代器*************")
for k,v in pairs(aa) do
    print("pairs迭代器遍历："..k.."_"..v)
end
