---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/11 22:29
---

print("******二维数组******")
print("******自定义索引******")
aa = {[0]=1,2,3,[1]=4,5,[2]=6}
print(aa[0])
print(aa[2])
print(#aa)
for i = 1, #aa do
    print(i.."="..aa[i])
end