---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/13 20:34
---

str = require("lesson07_Table5") --调用其他脚本的格式，此方法会调用该脚本的全局变量和函数等
--print("str：",str)
deLog("脚本加载")
print(package.loaded["lesson07_Table5"]) --判断是否加载了该脚本
package.loaded["lesson07_Table5"] = nil --该值设为空时卸载脚本
deLog("脚本卸载")
print(package.loaded["lesson07_Table5"])
local t08 = {{age = 10,name = "10"},{age = 12,name = "12"}}
delogTable(t08)

print("****************大G表*******************")
for k,v in pairs(_G) do  --_G是一个总表，他将我们声明的全局变量都存储在其中
    print(k,v)
end

print("****************引用表的返回*******************")
local str = require("lesson07_Table5") --return可以在外部获取一个希望得到的内容，一般情况下是局部变量
print(str.name)


