---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/12 17:44
---
function deLog(s)
    print("********"..s.."********")
end

deLog("字典的声明")
a = {["name"]="小红",["age"]=20,["type"]="student"}
print(a.name)
print(a["age"])
print(a.type)

a["lve"] = 100
a["name"] = "xiaohong"
a["type"] = "teacher"
a.lve = 99
print(a.lve)
print(a.name)
print(a.type)

deLog("字典的遍历")
for k,v in pairs(a) do
    print(k.." : "..v)
end

deLog("字典")