---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/19 15:31
---
require("function")

deLog("面向对象")
deLog("面向对象-封装")
--lua中,面向对象，类其实都是基于table来实现的
Object = {}
Object.id = 1 --这种调用类似于静态属性，因为lua中声明变量时，他是全局的

                              -- : 会自动调用这个函数的对象，作为第一个传入的写法
function Object:new()         -- 在Object中声明一个new()方法，并且把传入的第一个表当为self
                              -- self 代表的是我们默认传入的第一个参数
    local obj = {}
    setmetatable(obj,self)    -- 创建一个表，把他设置成传入的self的子表
    self.__index = self       -- 当子表需要读取信息时，从元表self中读取(仅限定于读取元素)
    return obj                --                                (还有当子表不存在该属性时)
end

local myObject = Object:new()
print(myObject)
print(myObject.id)
--myObject.id = "myObjectId"
--print(myObject.id)




















