---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 98425.
--- DateTime: 2022/3/11 22:55
---

 deLog = function (s)
    print("********"..s.."********")
end
function delogTable(aa)
    for k,v in ipairs(aa) do
        print("ipairs迭代器遍历："..k.."_"..v)
    end
end

deLog("无返回值")
--传入参数和需要的匹配不会报错
--只会丢弃或者报nil

deLog("有返回值")
--传入多余的参数时会丢弃
--返回多余的参数时可以多声明变量接取或者丢弃

deLog("函数的重载")
--函数名相同，参数类型不同 或者参数个数不同
--lua中后面相同名的参数会覆盖前面的相同名的参数，lua中不支持函数的重载
function F6()
    print("23333")
end
function F6(str)
    print(str)
end
F6()

deLog("可变长参数")
F7 = function (...)
    t = {...}
    delogTable(t)
end
F7(1,2,3,4,5,6,7,8)

deLog("函数嵌套")
--闭包
F8 = function(x)
    return function(y)
        print(x..y)
    end
end

f9 = F8("函数-")
f9("-闭包")